import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

import { Container } from "@mui/material";
import Banner from "../components/Banner";
import CardListsContainer from "../components/CardListsContainer";

import coffeeStoresData from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStoresData,
    },
  };
}

export default function Home({ data }) {
  const handleOnBannerBtnClick = () => {
    console.log("Hi, banner button");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoissure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container maxWidth="lg">
          <Banner
            buttonText={"Nearby Stores"}
            handleOnClick={handleOnBannerBtnClick}
          ></Banner>

          <CardListsContainer coffeeStoresData={coffeeStoresData} />
        </Container>
      </main>
    </div>
  );
}
