import { Container, Typography } from "@mui/material";
import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Card from "../components/Card";
import CardListsContainer from "../components/CardListsContainer";
import styles from "../styles/Home.module.css";

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log("Hi, banner button");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoissure</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Container maxWidth="lg">
          <Banner
            buttonText={"Nearby Stores"}
            handleOnClick={handleOnBannerBtnClick}
          ></Banner>

          <Typography
            variant="h3"
            marginBottom="50px"
            component="h2"
            sx={{ fontWeight: 700 }}
            align="center"
          >
            Toronto Stores
          </Typography>
          <CardListsContainer />
        </Container>
      </main>
    </div>
  );
}
